### ISSUE TITLE
Cannot run tintwizard 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [vanadey/tintwizard#35]
```
I have tried 0.2.8 and 0.2.9 and get:

Traceback (most recent call last):
  File "./tintwizard.py", line 2299, in <module>
    tw = TintWizardGUI()
  File "./tintwizard.py", line 313, in __init__
    self.uiManager.insert_action_group(self.ag)
TypeError: GtkUIManager.insert_action_group() takes exactly 2 arguments (1
given)


I am running Hardy with 
Boost.Python Library
Boost.Python Library development files
the python in python interpreter, C backend translation
the python in python interpreter, interpreted version
standard python library for pypy
Python Version 2.5
Header files and a static library for Python (v2.5)
Examples for the Python language (v2.5) 
Package depending on all supported Python runtime versions
Package depending on all supported Python development packages
Python bindings for the Cairo vector graphics library
Python cairo bindings: development files
Open GL based interactive canvas library - Python bindings
A Set of facilities to extend Python with C++
Python bindings for the GTK+ widget set (This package contains the bindings
for the version 2.0 of that toolkit.)
GTK+ bindings: devel files 
This archive contains files that allow you to build wrappers for addon
that interoperate python-gtk2 (pygtk).
Python Imaging Library
and many others. I see references all over the net about python-gtk2 being
the same as pygtk2 that you reference. I try to get to the site that is
supposed to have the pygtk2 package, and it is not up!

Any help would be appreciated :)
```

Original issue reported on code.google.com by `thebalsh...@gmail.com` on 9 Nov 2009 at 3:38

**Comment by vanadey** [comment]
Closing as fix has been confirmed by submitter.
